# Generated by Django 4.1.7 on 2023-03-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(default='no nicknames known', max_length=100)),
                ('origin', models.CharField(default='unknown origin', max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('staff_level', models.CharField(choices=[('unassigned', 'UNASSIGNED'), ('admiral', 'ADMIRAL'), ('captain', 'CAPTAIN'), ('XO', 'XO')], default='unassigned', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('armament', models.TextField(max_length=300)),
                ('engine_type', models.TextField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
    ]
